### ISSUE TITLE
Could you specify a license?

### ISSUE THREAD

**Issue by talwrii** [rnikoopour/WikiSearch#1]
Hey, 

I want to fork your repo and push some tweaks.
Is this okay with you? If so could you tell me what license I should use?
Here is a list of licenses that you might like to use: https://opensource.org/licenses

**Comment by rnikoopour** [comment]
Hey Talwrii,

I’ll add the license later today/tomorrow. 

It’s going to be a GPL license. I just need to see which version I want to use.

**Comment by talwrii** [comment]
Cool cool. GPL is great for me. Thanks for that (and for the useful tool - you saved me the time of having to code this myself).

The changes I've got:

* Make this installable with pip and with an entry point
* Make this python 3 compatible
* Add flags to show and hide the table of contents for use with scripting

This is to make the tool easier to use from my window manager (highlight word, press key, get summary of meaning).

I'll throw you a pull request to see if you want to merge the changes but you should feel free not to ( I sometimes fell people who post useful code on the internet get punished by having other people as them for features and submit bugs when the code works fine for them!)

**Comment by rnikoopour** [comment]
Hey dude!

I added the GPLv3 license.

Feel free to submit a PR with your changes =D 

Glad this project was useful for you.
